### PR TITLE
The README file in this repo has a bad link - [404:NotFound]

### PR DESCRIPTION
**Pull request by MrCull**
## PR summary

The markup version of the readme that is displayed for the main page in this repo contains the following bad link:

"Node.js SDK Core document about authentication"
Status code [404:NotFound] - Link: https://github.com/IBM/node-sdk-core/blob/master/Authentication.md

It looks like case is important for links in GitHub and it should be:
https://github.com/IBM/node-sdk-core/blob/master/AUTHENTICATION.md

Fixes: #77

## PR Checklist

Please make sure that your PR fulfills the following requirements:

- [It does not look like other commits in this repo follow this!?] The commit message follows the
[Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [N/A] Tests for the changes have been added (for bug fixes / features)
- [N/A] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [x] Documentation content changes
- [ ] Other (please describe)

## What is the current behavior?
Bad link

## What is the new behavior?
Working link

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

N/A

**Extra**

This bad link was found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

Re-check this Repo using the tool’s website: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fIBM%2fcloudant-node-sdk

If you have any feedback on the tool itself, or the information provided here, then please feel free to share your thoughts by adding a comment here, or adding a “Discussions” comment in the tool’s Repo.

### CODE REVIEW

**Comment by bessbd** [comment]
Hi @MrCull ,

Thank you for this PR!
The change you're proposing here looks good and fixes the issue, but for the sake of consistency, I believe the upstream repo `node-sdk-core` is to be changed. To do that, I've just opened https://github.com/IBM/node-sdk-core/pull/117 . What do you think?

Btw, I think the issue link here should be https://github.com/IBM/cloudant-node-sdk/issues/77

**Comment by MrCull** [comment]
Hi @bessbd, 
Thanks for the quick response 👍 

Yeah it should be #77. Sorry, I'm not sure how that typo was made!

Ah cool, yeah your IBM/node-sdk-core#117 should fix it!
Hopefully there are no other repos referencing that file in the upper case or else they would then get a broken link too.

Feel free to close of this PR if your solution in the upstream is used.

**Comment by bessbd** [comment]
I'll wait for a response on https://github.com/IBM/node-sdk-core/pull/117 and close this one once https://github.com/IBM/node-sdk-core/pull/117 is merged.
In case there is a concern about links, we can leave a note of "this file has been moved". Let's see what they think in `node-sdk-core`.

**Comment by bessbd** [comment]
https://github.com/IBM/node-sdk-core/pull/117 is now merged, so I'm closing this PR.
Thank you for bringing this to our attention, @MrCull !

**Pull request closed without merging**
