### PR TITLE
Fix gzip compression option

### PR DESCRIPTION
**Pull request by emlaver**
## PR summary

Fixes: #176 

**Note: An existing issue is [required](https://github.com/IBM/cloudant-node-sdk/blob/master/CONTRIBUTING.md#PRs) before opening a PR.**

## PR Checklist

Please make sure that your PR fulfills the following requirements:

- [x] The commit message follows the
[Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [ ] Documentation content changes
- [ ] Other (please describe)

## What is the current behavior?
Setting `false` in `setEnableGzipCompression` has no effect.

## What is the new behavior?
Setting `false` in `setEnableGzipCompression` will disable gzip compression for requests.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by eiri — COMMENTED** [review]
I'm not very familiar with `cloudantBaseService` implementation, so bear with me - two questions:
- Is `baseOptions` copied to instance of "our" base service? I'm not sure why it need an explicit set there after super call.
- Do we also need positive tests, i.e. for when we call `setEnableGzipCompression(true)`, just to confirm that we actually changing the attribute value?

**Comment by emlaver** [comment]
> I'm not very familiar with `cloudantBaseService` implementation, so bear with me - two questions:
> 
> * Is `baseOptions` copied to instance of "our" base service? I'm not sure why it need an explicit set there after super call.

@eiri We shouldn't have to but in the core the `setEnableGzipCompression` applies the setting directly to the requestWrapperInstance and [does not persist it into the options object](https://github.ibm.com/arf/planning-sdk-squad/issues/2522).
> * Do we also need positive tests, i.e. for when we call `setEnableGzipCompression(true)`, just to confirm that we actually changing the attribute value?

Given that we originally expected the setter to work, I wanted to have a sanity test to verify that setting the gzip compression flag does in fact get set on a) the request wrapper and b) the base options object.

**Review by vmatyusGitHub — APPROVED** [review]
LGTM +1

**Comment by eiri** [comment]
> Given that we originally expected the setter to work, I wanted to have a sanity test to verify that setting the gzip compression flag does in fact get set on a) the request wrapper and b) the base options object.

Right, I'm not arguing that we don't need the test, I'm asking if we need to add a test for setting compression to `true` and confirm that both attributes actually changed, if this setting is `false` by default then we'll miss a case when setter function is not working.

**Review by eiri — APPROVED** [review]
Looks good to me, apart from the linter's complains.  Also thank you for updating those tests

**Pull request merged**
