### PR TITLE
Dependabot cherry pick

### PR DESCRIPTION
**Pull request by mojito317**
## PR summary

Gather dependabot PRs into one PR.

## PR Checklist

Please make sure that your PR fulfills the following requirements:

- [ ] The commit message follows the
[Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [ ] Documentation content changes
- [x] Other (please describe)

## What is the current behavior?
This PR has all the commits from dependabot PRs:

https://github.com/IBM/cloudant-node-sdk/pull/36 -> @semantic-release/changelog (dev)
https://github.com/IBM/cloudant-node-sdk/pull/35 -> @types/node
https://github.com/IBM/cloudant-node-sdk/pull/34 -> jest (dev)
https://github.com/IBM/cloudant-node-sdk/pull/33 -> codecov (dev)
https://github.com/IBM/cloudant-node-sdk/pull/32 -> prettier (dev)

## What is the new behavior?
This PR bumps the dependencies to the versions mentioned in the commit messsages.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by vmatyusGitHub** [comment]
The change looks good, but the pipeline has some problem. Have you check it?

**Comment by emlaver** [comment]
There's several errors from the `eslint` command e.g.
```
/home/travis/build/IBM/cloudant-node-sdk/scripts/report_integration_test.js
410  30:57  error  Replace `suite` with `(suite)`    prettier/prettier
411  37:18  error  Replace `suite` with `(suite)`    prettier/prettier
412  38:54  error  Replace `test` with `(test)`      prettier/prettier
413  45:20  error  Replace `result` with `(result)`  prettier/prettier
414  80:12  error  Replace `error` with `(error)`    prettier/prettier
```

**Comment by mojito317** [comment]
Thanks @vmatyusGitHub and @emlaver. I fixed the eslint issues in  08ec11d.

**Review by emlaver — APPROVED** [review]

**Review by vmatyusGitHub — APPROVED** [review]
LGTM +1

**Comment by mojito317** [comment]
Thanks for the reviews @emlaver and @vmatyusGitHub! I'm about to merge this.

**Pull request merged**
